# =========================
# Main file for Elinsz 3D
#
# by Elio Inoc. Souza, www.elinsz3d.com.br, mail@suporte.elinsz3d.com.br
#
# DO NOT EDIT THIS FILE IN THE Elinsz, IT WILL STRIP SOME OF THE CODE!!!
# =========================


require 'sketchup.rb'


## =====================


module EZS_Extensions

  module EZS_Elinsz


    # Creates new class
    class Elinsz < UI::WebDialog


        # Initialize class and callbacks
        def initialize


          ## =====================

          ## Set some variables

          # Get this file's directory w/ backcomp for "//" in file path
          @base_dir = File.dirname(__FILE__).gsub(%r{//}) { "/" }

          # Get user directory
          @user_dir = (ENV['USERPROFILE'] != nil) ? ENV['USERPROFILE'] :
            ((ENV['HOME'] != nil) ? ENV['HOME'] : @base_dir )

          # Get working directory from last file - set to user directory otherwise
          @last_file = Sketchup.read_default "ezs_Elinsz3D", "last_file"
          @last_file != nil ? @snip_dir = File.dirname(@last_file) : @snip_dir = @user_dir


          ## =====================

          ## Set up the WebDialog interface

          # Dialog parameters
          super "Elinsz 3D", false, "Elinsz3D", 750, 600, 100, 100, true

          # Set HTML UI file for WebDialog
          ui_loc = File.join( @base_dir , "elinsz.html" )
          set_file( ui_loc )
          navigation_buttons_enabled = false
          min_width = 500
          min_height = 500


          ## =====================

          ## Show the dialog and run the new routine

          show do

            # Set version number in about dlg
            execute_script("var rceVersion = #{EZS_Elinsz::EXTVERSION.to_s}")
            execute_script("$('#version').text( rceVersion )")

            Sketchup.status_text = "#{EZS_Elinsz::EXTTITLE} | Welcome!"

          end  # show


          ## =====================

          ## Callback to show HELP dialog in browser

          add_action_callback("help") do |dlg, params|

            EZS_Elinsz::browser( "#{EZS_Elinsz::EXTTITLE} - Help" , "https://www.Elinsz.com.br" )

          end  # add_action_callback("help")


          ## =====================

          ## Callback to show REFERENCE BROWSER dialog

          add_action_callback("browser") do |dlg, params|

            EZS_Elinsz::browser( "#{EZS_Elinsz::EXTTITLE} - Reference Browser" , File.join( EZS_Elinsz::EXTDIR , 'ezs_elinsz' , 'ui-browser.html' ) , true )

          end  # add_action_callback("browser")


       end # initialize


    end # class Elinsz


    ## =====================

    ## Show local or remote website either as a WebDialog or HtmlDialog

    def self.browser( title , loc , isfile = false )

      if Sketchup.version.to_f < 17 then  # Use old WebDialog method
        @dlg = UI::WebDialog.new( title , true ,
          title.gsub(/\s+/, "_") , 1000 , 600 , 100 , 100 , true);
        @dlg.navigation_buttons_enabled = false
        isfile ? @dlg.set_file( loc ) : @dlg.set_url( loc )
        @dlg.show
      else  # Use new HtmlDialog
        @dlg = UI::HtmlDialog.new( { :dialog_title => title, :width => 1000, :height => 600,
          :style => UI::HtmlDialog::STYLE_DIALOG, :preferences_key => title.gsub(/\s+/, "_") } )
        isfile ? @dlg.set_file( loc ) : @dlg.set_url( loc )
        @dlg.show
        @dlg.center
      end

    end  # def self.browser


    ## =====================

    ## Add menu items

    unless file_loaded?(__FILE__)

      # Add main menu items
      sub = UI.menu("Window").add_submenu( "Elinsz 3D" )
      sub.add_item("Elinsz 3D") { editordlg = EZS_Elinsz::Elinsz.new }
      sub.add_item("Reference Browser") { self.browser( "#{EZS_Elinsz::EXTTITLE} - Reference Browser" , File.join('ezs_elinsz','App','ui-browser.html' ) , true ) }
      sub.add_item("Help") { self.browser( "#{EZS_Elinsz::EXTTITLE} - Help" , "https://www.Elinsz.com.br" ) }

      # Add toolbar
      as_rce_tb = UI::Toolbar.new "Elinsz 3D"
      as_rce_cmd = UI::Command.new("Elinsz 3D") { editordlg = EZS_Elinsz::Elinsz.new }
      # One instance only version:
      # as_rce_cmd = UI::Command.new("Elinsz 3D") { editordlg = EZS_Elinsz::Elinsz.new unless editordlg }
      if Sketchup.version.to_i >= 16
        if RUBY_PLATFORM =~ /darwin/
          as_rce_cmd.small_icon = "Img/elinsz.pdf"
          as_rce_cmd.large_icon = "Img/elinsz.pdf"
        else
          as_rce_cmd.small_icon = "Img/elinsz.svg"
          as_rce_cmd.large_icon = "Img/elinsz.svg"
        end
      else
        as_rce_cmd.small_icon = "Img/elinsz_16.png"
        as_rce_cmd.large_icon = "Img/elinsz_24.png"
      end
      as_rce_cmd.tooltip = "Elinsz 3D"
      as_rce_cmd.status_bar_text = "Projeto paramétrico para sistemas Modulares"
      as_rce_cmd.menu_text = "Elinsz 3D"
      as_rce_tb = as_rce_tb.add_item as_rce_cmd
      as_rce_tb.show

      # Tell SU that we loaded this file
      file_loaded(__FILE__)

    end  # unless


    ## =====================


  end  # module EZS_Elinsz

end  # module EZS_Extensions


## =====================
